# Generated by Django 3.0.6 on 2020-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogHP', '0002_auto_20200628_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivement',
            name='published_year',
        ),
        migrations.AddField(
            model_name='achivement',
            name='issue',
            field=models.CharField(blank=True, max_length=200, verbose_name='ジャーナル掲載号'),
        ),
        migrations.AddField(
            model_name='recruiting',
            name='conditions',
            field=models.CharField(blank=True, max_length=200, verbose_name='実験条件'),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='author',
            field=models.CharField(max_length=500, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='journal',
            field=models.CharField(max_length=200, verbose_name='ジャーナル名'),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='pages',
            field=models.CharField(blank=True, default='pp.', max_length=50, verbose_name='ジャーナル掲載ページ'),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='year',
            field=models.CharField(max_length=50, verbose_name='発表年度'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='apply_link',
            field=models.URLField(blank=True, verbose_name='募集URL'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='duration_hour',
            field=models.DurationField(verbose_name='実験時間'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='exp_grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='実験者の学年'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='experimenter',
            field=models.CharField(blank=True, max_length=200, verbose_name='実験者'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='period_end',
            field=models.DateField(verbose_name='実験終了日時'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='period_start',
            field=models.DateField(verbose_name='実験開始日時'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='place',
            field=models.CharField(max_length=200, verbose_name='実験場所'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='precautions',
            field=models.TextField(default='※事前アンケートあり（アンケートの結果，実験参加者として採用されない場合がございます．ご了承ください．）', verbose_name='注意事項'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='reward',
            field=models.CharField(blank=True, max_length=200, verbose_name='報酬'),
        ),
        migrations.AlterField(
            model_name='recruiting',
            name='title',
            field=models.CharField(max_length=200, verbose_name='募集タイトル'),
        ),
    ]
