# Generated by Django 3.0.6 on 2020-07-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogHP', '0004_auto_20200709_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiting',
            name='conditions',
            field=models.CharField(default='特になし', max_length=200, verbose_name='実験条件'),
        ),
    ]
